#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
app_etudiant_by_region:
    path: '/etudiants/{region}'
    controller: 'App\Controller\EtudiantController::showByRegion'
